# Generated by Django 3.1.2 on 2020-10-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameModel',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('year_Published', models.IntegerField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('minplaytime', models.IntegerField()),
                ('maxplaytime', models.IntegerField()),
                ('minage', models.IntegerField()),
                ('language_dependency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedPlayerAgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalvotes', models.IntegerField()),
                ('best_playerage', models.IntegerField()),
                ('secondbest_playerage', models.IntegerField()),
                ('thirdbest_playerage', models.IntegerField()),
                ('id_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bgg_recommender.boardgamemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedNumPlayersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalvotes', models.IntegerField()),
                ('best_numvotes', models.IntegerField()),
                ('recommended_numvotes', models.IntegerField()),
                ('recommended_numplayers', models.IntegerField()),
                ('notrecommended_numvotes', models.IntegerField()),
                ('notrecommended_numplayers', models.IntegerField()),
                ('id_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bgg_recommender.boardgamemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGamePublisherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameMechanicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.CharField(max_length=200)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameInegrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_integration', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameImplementationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_implementation', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameExpansionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_expansion', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameDesignerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameCompilationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compilation', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameArtistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_product', models.ManyToManyField(to='bgg_recommender.BoardGameModel')),
            ],
        ),
    ]
