# Generated by Django 3.1.2 on 2020-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamemodel',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='maxplaytime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='minage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='minplaytime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='year_Published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
