# Generated by Django 3.1.2 on 2020-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0002_auto_20201027_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamemodel',
            name='language_dependency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
