# Generated by Django 3.1.2 on 2020-10-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0004_auto_20201027_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamemodel',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameArtistModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameCategoryModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='compilations',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameCompilationModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='designers',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameDesignerModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='expansions',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameExpansionModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='families',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameFamily'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='implementations',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameImplementationModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='integrations',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameInegrationModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='mechanics',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGameMechanicModel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='publishers',
            field=models.ManyToManyField(blank=True, null=True, to='bgg_recommender.BoardGamePublisherModel'),
        ),
    ]
