# Generated by Django 3.1.2 on 2020-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0006_auto_20201027_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestednumplayersmodel',
            name='best_numplayers',
            field=models.IntegerField(null=True),
        ),
    ]
