# Generated by Django 3.1.2 on 2020-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0007_suggestednumplayersmodel_best_numplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestednumplayersmodel',
            name='best_numplayers',
            field=models.IntegerField(),
        ),
    ]
