# Generated by Django 3.1.2 on 2020-10-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0008_auto_20201030_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestednumplayersmodel',
            name='best_numplayers',
            field=models.IntegerField(null=True),
        ),
    ]
