# Generated by Django 3.1.2 on 2020-11-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0009_auto_20201030_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingBoardGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('bayesaverage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatBoardGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersrated', models.IntegerField()),
                ('average', models.FloatField()),
                ('stddev', models.FloatField()),
                ('owned', models.IntegerField()),
                ('trading', models.IntegerField()),
                ('wanting', models.IntegerField()),
                ('wishing', models.IntegerField()),
                ('numcomments', models.IntegerField()),
                ('numweights', models.IntegerField()),
                ('averageweight', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='suggestednumplayersmodel',
            old_name='best_numvotes',
            new_name='best',
        ),
        migrations.RenameField(
            model_name='suggestednumplayersmodel',
            old_name='notrecommended_numplayers',
            new_name='not_recommended',
        ),
        migrations.RenameField(
            model_name='suggestednumplayersmodel',
            old_name='notrecommended_numvotes',
            new_name='recommended',
        ),
        migrations.RenameField(
            model_name='suggestednumplayersmodel',
            old_name='recommended_numplayers',
            new_name='votes_num',
        ),
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='best_numplayers',
        ),
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='recommended_numvotes',
        ),
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='totalvotes',
        ),
        migrations.AddField(
            model_name='boardgamemodel',
            name='ranks',
            field=models.ManyToManyField(blank=True, to='bgg_recommender.RankingBoardGameModel'),
        ),
        migrations.AddField(
            model_name='boardgamemodel',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgg_recommender.statboardgamemodel'),
        ),
    ]
