# Generated by Django 3.1.2 on 2020-11-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0011_auto_20201108_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statboardgamemodel',
            old_name='averageweight',
            new_name='average_weight',
        ),
        migrations.RenameField(
            model_name='statboardgamemodel',
            old_name='numcomments',
            new_name='num_comments',
        ),
        migrations.RenameField(
            model_name='statboardgamemodel',
            old_name='numweights',
            new_name='num_weights',
        ),
    ]
