# Generated by Django 3.1.2 on 2020-11-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0012_auto_20201108_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgamemodel',
            name='ranks',
        ),
        migrations.AddField(
            model_name='boardgamemodel',
            name='ranks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgg_recommender.rankingboardgamemodel'),
        ),
        migrations.AlterField(
            model_name='boardgamemodel',
            name='suggested_num_players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgg_recommender.suggestednumplayersmodel'),
        ),
    ]
