# Generated by Django 3.1.2 on 2020-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0013_auto_20201108_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='best',
        ),
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='not_recommended',
        ),
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='recommended',
        ),
        migrations.RemoveField(
            model_name='suggestednumplayersmodel',
            name='votes_num',
        ),
        migrations.AddField(
            model_name='suggestednumplayersmodel',
            name='vote_num_players_dict',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
