# Generated by Django 3.1.2 on 2020-11-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgg_recommender', '0015_auto_20201108_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardGameInegrationModel',
            new_name='BoardGameIntegrationModel',
        ),
    ]
